routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

Route::middleware(['auth', 'checkUserSession'])->prefix('administracion')->group(function() {
    
    Route::prefix('/')->name('home.')->group(function () {

        Route::get('/', 'Admin\HomeController@index')->name('index');

        Route::get('profile', 'Admin\HomeController@profile')->name('profile');

        Route::post('profile', 'Admin\HomeController@updateProfile')->name('update-profile');

        Route::post('cancel', 'Admin\HomeController@cancel')->name('cancel');
    });

    Route::prefix('crm')->name('crm.')->group(function () {

        Route::prefix('facturas')->name('invoices.')->group(function () {

            Route::get('/', 'Admin\FacturasController@index')->middleware(['role:superadministrador|administrador'])->name('index');

            Route::get('{id}/detalle', 'Admin\FacturasController@show')->middleware(['role:superadministrador|administrador|vendedor'])->name('show');

            Route::get('{id}/editar', 'Admin\FacturasController@edit')->middleware(['role:superadministrador|administrador'])->name('edit');

            Route::post('{id}/editar', 'Admin\FacturasController@update')->middleware(['role:superadministrador|administrador'])->name('update');

            Route::post('{id}/aprobar', 'Admin\FacturasController@approve')->middleware(['role:superadministrador|administrador'])->name('approve');

            Route::post('{id}/anular', 'Admin\FacturasController@cancel')->middleware(['role:superadministrador|administrador'])->name('cancel');
        });

        Route::prefix('clientes')->middleware(['role:superadministrador|administrador'])->name('clients.')->group(function () {

            Route::get('/', 'Admin\ClientesController@index')->name('index');

            Route::get('pendientes', 'Admin\ClientesController@indexPending')->name('index-pending');

            Route::get('nuevo', 'Admin\ClientesController@create')->name('create');

            Route::post('nuevo', 'Admin\ClientesController@store')->name('store');

            Route::get('{id}/ficha', 'Admin\ClientesController@show')->name('show');

            Route::get('{id}/editar', 'Admin\ClientesController@edit')->name('edit');

            Route::post('{id}/editar', 'Admin\ClientesController@update')->name('update');

            Route::post('{id}/eliminar', 'Admin\ClientesController@delete')->name('delete');

            Route::post('{id}/activar', 'Admin\ClientesController@activate')->name('activate');

            Route::post('{id}/suspender', 'Admin\ClientesController@suspend')->name('suspend');

            Route::post('{id}/anular', 'Admin\ClientesController@cancel')->name('cancel');

            Route::post('{id}/contactar', 'Admin\ClientesController@contact')->name('contact');

            Route::prefix('{id}/evaluaciones')->middleware(['role:superadministrador|administrador'])->name('evaluations.')->group(function () {

                Route::prefix('entrenamientos')->middleware(['role:superadministrador|administrador'])->name('trainers.')->group(function () {

                    Route::get('/', 'Admin\EvaluacionesController@trainers')->name('index');

                    Route::get('nuevo', 'Admin\EvaluacionesController@createTrainers')->name('create');

                    Route::post('nuevo', 'Admin\EvaluacionesController@storeTrainers')->name('store');

                    Route::get('{evaluation}/editar', 'Admin\EvaluacionesController@editTrainers')->name('edit');

                    Route::post('{evaluation}/editar', 'Admin\EvaluacionesController@updateTrainers')->name('update');

                    Route::post('{evaluation}/eliminar', 'Admin\EvaluacionesController@deleteTrainers')->name('delete');
                });

                Route::prefix('nutricionistas')->middleware(['role:superadministrador|administrador'])->name('nutritionists.')->group(function () {
    
                    Route::get('/', 'Admin\EvaluacionesController@nutritionist')->name('index');

                    Route::get('nuevo', 'Admin\EvaluacionesController@createNutritionist')->name('create');

                    Route::post('nuevo', 'Admin\EvaluacionesController@storeNutritionist')->name('store');

                    Route::get('{evaluation}/editar', 'Admin\EvaluacionesController@editNutritionist')->name('edit');

                    Route::post('{evaluation}/editar', 'Admin\EvaluacionesController@updateNutritionist')->name('update');

                    Route::post('{evaluation}/eliminar', 'Admin\EvaluacionesController@deleteNutritionist')->name('delete');
                });

                Route::prefix('{evaluation}/items')->middleware(['role:superadministrador|administrador'])->name('items.')->group(function () {

                    Route::post('{item}/editar', 'Admin\EvaluacionesController@updateItem')->name('update');

                    Route::post('{item}/eliminar', 'Admin\EvaluacionesController@deleteItem')->name('delete');
                });
            });
        });

        Route::prefix('entrenadores')->middleware(['role:superadministrador|administrador'])->name('trainers.')->group(function () {

            Route::get('/', 'Admin\EntrenadoresController@index')->name('index');

            Route::get('nuevo', 'Admin\EntrenadoresController@create')->name('create');

            Route::post('nuevo', 'Admin\EntrenadoresController@store')->name('store');

            Route::get('{id}/detalle', 'Admin\EntrenadoresController@detail')->name('detail');

            Route::get('{id}/editar', 'Admin\EntrenadoresController@edit')->name('edit');

            Route::post('{id}/editar', 'Admin\EntrenadoresController@update')->name('update');

            Route::post('{id}/eliminar', 'Admin\EntrenadoresController@delete')->name('delete');

            Route::post('{id}/activar', 'Admin\EntrenadoresController@activate')->name('activate');

            Route::post('{id}/suspender', 'Admin\EntrenadoresController@suspend')->name('suspend');

            Route::post('{id}/anular', 'Admin\EntrenadoresController@cancel')->name('cancel');
        });

        Route::prefix('nutricionistas')->middleware(['role:superadministrador|administrador'])->name('nutritionists.')->group(function () {

            Route::get('/', 'Admin\NutricionistasController@index')->name('index');

            Route::get('nuevo', 'Admin\NutricionistasController@create')->name('create');

            Route::post('nuevo', 'Admin\NutricionistasController@store')->name('store');

            Route::get('{id}/detalle', 'Admin\NutricionistasController@detail')->name('detail');

            Route::get('{id}/editar', 'Admin\NutricionistasController@edit')->name('edit');

            Route::post('{id}/editar', 'Admin\NutricionistasController@update')->name('update');

            Route::post('{id}/eliminar', 'Admin\NutricionistasController@delete')->name('delete');

            Route::post('{id}/activar', 'Admin\NutricionistasController@activate')->name('activate');

            Route::post('{id}/suspender', 'Admin\NutricionistasController@suspend')->name('suspend');

            Route::post('{id}/anular', 'Admin\NutricionistasController@cancel')->name('cancel');
        });

        /*Route::prefix('informes')->middleware(['role:superadministrador|administrador'])->name('reports.')->group(function () {

            Route::get('/', 'Admin\InformesController@index')->name('index');

            Route::get('proccess', 'Admin\InformesController@proccess')->name('proccess');
        });*/
    });

    Route::prefix('configuracion')->name('configuration.')->group(function () {

        Route::prefix('planes')->middleware(['role:superadministrador|administrador'])->name('plans.')->group(function () {

            Route::get('/', 'Admin\PlanesController@index')->name('index');

            Route::get('nuevo', 'Admin\PlanesController@create')->name('create');

            Route::post('nuevo', 'Admin\PlanesController@store')->name('store');

            Route::get('{id}/editar', 'Admin\PlanesController@edit')->name('edit');

            Route::post('{id}/editar', 'Admin\PlanesController@update')->name('update');

            Route::post('{id}/eliminar', 'Admin\PlanesController@delete')->name('delete');

            Route::post('{id}/suspender', 'Admin\PlanesController@suspend')->name('suspend');

            Route::post('{id}/activar', 'Admin\PlanesController@activate')->name('activate');
        });

        Route::prefix('usuarios')->middleware(['role:superadministrador|administrador'])->name('users.')->group(function () {

            Route::get('/', 'Admin\UsuariosController@index')->name('index');

            Route::get('nuevo', 'Admin\UsuariosController@create')->name('create');

            Route::post('nuevo', 'Admin\UsuariosController@store')->name('store');

            Route::get('{id}/editar', 'Admin\UsuariosController@edit')->name('edit');

            Route::post('{id}/editar', 'Admin\UsuariosController@update')->name('update');

            Route::post('{id}/eliminar', 'Admin\UsuariosController@delete')->name('delete');

            Route::post('{id}/suspender', 'Admin\UsuariosController@suspend')->name('suspend');

            Route::post('{id}/activar', 'Admin\UsuariosController@activate')->name('activate');
        });        
    });
});

app/Models/Cliente.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Cliente extends Model
{
    use SoftDeletes;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'cliente';

    protected $fillable = [
        'codigo', 'nombre', 'apellido', 'rut', 'telefono', 'telefono_extra', 'fecha_nacimiento', 
        'peso', 'altura', 'direccion', 'comuna_id', 'cliente_estado_id', 'user_id', 'observaciones'
    ];

    protected $dates = [
        'fecha_nacimiento', 'created_at', 'updated_at', 'deleted_at'
    ];

    public static function boot()
    {
        parent::boot();

        static::deleted(function ($model) {
            //Cancel Suscription
            $model->user->subscription('main')->cancel();

            //Delete User
            $model->user->delete();
        });
    }

    public function comuna()
    {
        return $this->belongsTo(\App\Models\Comuna::class, 'comuna_id');
    }

    public function user()
    {
        return $this->belongsTo(\App\User::class, 'user_id');
    }

    public function estado()
    {
        return $this->belongsTo(\App\Models\ClienteEstado::class, 'cliente_estado_id');
    }

    public function facturasCliente()
    {
        return $this->hasMany(\App\Models\Factura::class, 'cliente_id');
    }

    public function evaluacionesCliente()
    {
        return $this->hasMany(\App\Models\Evaluacion::class, 'cliente_id');
    }

    public function getFullName()
    {
        return $this->nombre . ' ' . $this->apellido;
    }
}

app/Http/Controllers/Admin/ClientesController.php
<?php

namespace App\Http\Controllers\Admin;

use Exception;
use App\Events\ContactClientEvent;
use App\Globals\Alerts;
use App\Http\Controllers\Controller;
use App\Http\Requests\CreateClientRequest;
use App\Http\Requests\EditClientRequest;
use App\Repositories\Clientes\ClientesRepoI;
use App\Repositories\Planes\PlanesRepoI;
use App\Repositories\Regiones\RegionesRepoI;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ClientesController extends Controller
{
    protected $clientesRepo, $planesRepo, $regionesRepo;

    public function __construct(ClientesRepoI $clientesRepo, PlanesRepoI $planesRepo, RegionesRepoI $regionesRepo)
    {
        $this->clientesRepo = $clientesRepo;
        $this->planesRepo = $planesRepo;
        $this->regionesRepo = $regionesRepo;
    }

    public function index()
    {
        $clientes = $this->clientesRepo->getAllClients();

        return view('admin.crm.clientes.index', [
            'clientes' => $clientes
        ]);
    }

    public function indexPending()
    {
        $clientes = $this->clientesRepo->getAllPendingClients();

        return view('admin.crm.clientes.pendientes', [
            'clientes' => $clientes
        ]);
    }

    public function create()
    {
        $planes = $this->planesRepo->getAllPlans(1);
        $regiones = $this->regionesRepo->getRegionsList();

        return view('admin.crm.clientes.create', [
            'planes'   => $planes,
            'regiones' => $regiones
        ]);
    }

    public function store(CreateClientRequest $request)
    {
        $data = $request->except(['_token', 'region', 'comuna', 'email', 'password', 'password_confirmation', 'plan']);
        $dataUser = $request->only(['email', 'password']);

        //Format fields
        $data['fecha_nacimiento'] = date('Y-m-d', strtotime($data['fecha_nacimiento']));
        $data['comuna_id'] = $request->post('comuna');
        //Crypt Password
        $dataUser['password'] = bcrypt($dataUser['password']);
        
        $this->clientesRepo->store($data, $dataUser, $request->post('plan'));

        return redirect()->route('crm.clients.index')
            ->with('message', Alerts::CREATE_SUCCESS)
            ->with('messageType', 'success');
    }

    public function show($id)
    {
        $cliente = $this->clientesRepo->with(['comuna'])->findOneBy(['id' => $id]);
        $estadosCliente = $this->clientesRepo->getAllClientStatus();
        $regiones = $this->regionesRepo->getRegionsList();

        return view('admin.crm.clientes.show', [
            'cliente'        => $cliente,
            'estadosCliente' => $estadosCliente,
            'regiones'       => $regiones
        ]);
    }

    public function edit($id)
    {
        $cliente = $this->clientesRepo->with(['comuna'])->findOneBy(['id' => $id]);
        $estadosCliente = $this->clientesRepo->getAllClientStatus();
        $regiones = $this->regionesRepo->getRegionsList();

        return view('admin.crm.clientes.edit', [
            'cliente'        => $cliente,
            'estadosCliente' => $estadosCliente,
            'regiones'       => $regiones
        ]);
    }

    public function update($id, EditClientRequest $request)
    {
        $data = $request->except(['_token', 'region', 'comuna']);
        $data['comuna_id'] = $request->get('comuna');

        $this->clientesRepo->updateBy(['id' => $id], $data);

        return redirect()->back()
            ->with('message', Alerts::UPDATE_SUCCESS)
            ->with('messageType', 'success');
    }

    public function delete($id, Request $request)
    {
        $this->clientesRepo->deleteClient($id);

        return redirect()->route('crm.clients.index')
            ->with('message', Alerts::DELETE_SUCCESS)
            ->with('messageType', 'success');
    }

    public function activate($id, Request $request)
    {
        $this->clientesRepo->activate(($id));

        return redirect()->route('crm.clients.index')
            ->with('message', Alerts::ACTIVATE_SUCCESS)
            ->with('messageType', 'success');
    }

    public function suspend($id, Request $request)
    {
        $this->clientesRepo->suspend($id);

        return redirect()->route('crm.clients.index')
            ->with('message', Alerts::SUSPEND_SUCCESS)
            ->with('messageType', 'success');
    }

    public function cancel($id, Request $request)
    {
        $this->clientesRepo->cancel($id);

        return redirect()->route('crm.clients.index')
            ->with('message', Alerts::CANCEL_SUCCESS)
            ->with('messageType', 'success');
    }

    public function contact($id, Request $request)
    {
        try {

            $fileName = null;

            if (isset($request->file) && $request->hasFile('file') && $request->file('file')->isValid()) {
                $file = $request->file('file');
                //Store File
                $fileName = $file->getClientOriginalName();

                Storage::disk('public')->putFileAs('temp/', $file, $fileName);
            }

            //Contact Event
            event(new ContactClientEvent($id, $request->post('asunto'), $request->post('mensaje'), $fileName));

            return redirect()->back()
                ->with('message', 'Mensaje enviado correctamente')
                ->with('messageType', 'success');

        } catch (Exception $e) {
            throw $e;
        }
    }

    public function contactInformation($id)
    {
        $cliente = $this->clientesRepo->findOneBy(['id' => $id]);
        $estadosCliente = $this->clientesRepo->getAllClientStatus();

        return view('admin.crm.clientes.profile', [
            'cliente'        => $cliente,
            'estadosCliente' => $estadosCliente
        ]);
    }

    public function updateContactInformation($id, EditClientRequest $request)
    {
        $data = $request->except(['_token', 'pais', 'estado']);
        $data['pais_id'] = $request->get('pais');
        $data['cliente_estado_id'] = $request->get('estado');

        $this->clientesRepo->updateBy(['id' => $id], $data);

        return redirect()->back()
            ->with('message', Alerts::UPDATE_SUCCESS)
            ->with('messageType', 'success');
    }
}

resources/views/admin/crm/clientes/index.blade.php
@extends('admin.template.base')

@section('styles')

	@parent
	<!-- JQuery DataTable Css -->
    <link href="{{ asset('assets/admin/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}" rel="stylesheet" />    
	
@endsection

@section('content')

    <div class="row clearfix">
        <div class="col-xs-12">
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('home.index') }}">
                        <i class="material-icons">home</i>&nbsp;Inicio
                    </a>
                </li>
                <li class="active">
                    <i class="material-icons">work</i>&nbsp;Clientes
                </li>
            </ol>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        LISTADO DE CLIENTES
                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="{{ route('crm.clients.create') }}">Agregar Cliente</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                            <thead>
                                <tr>
                                    <th>Nombre Completo</th>
                                    <th>Email</th>
                                    <th>Teléfono</th>
                                    <th>RUT</th>
                                    <th>Estado</th>
                                    <th>Creado</th>
                                    <th>Modificado</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>Nombre Completo</th>
                                    <th>Email</th>
                                    <th>Teléfono</th>
                                    <th>RUT</th>
                                    <th>Estado</th>
                                    <th>Creado</th>
                                    <th>Modificado</th>
                                    <th>Acciones</th>
                                </tr>
                            </tfoot>
                            <tbody>
                                @foreach($clientes as $cliente)
                                    <tr>
                                        <td><a href="{{ route('crm.clients.show', $cliente->id) }}">{{ $cliente->getFullName() }}</a></td>
                                        <td>
                                            @if(!empty($cliente->user))
                                                <a href="mailto:{{ $cliente->user->email }}">{{ $cliente->user->email }}</a>
                                            @else
                                                &nbsp;
                                            @endif                                            
                                        </td>
                                        <td><a href="tel:{{ $cliente->telefono }}">{{ $cliente->telefono }}</a></td>
                                        <td>{{ $cliente->rut }}</td>
                                        <td>{{ $cliente->estado->nombre }}</td>
                                        <td>{{ $cliente->created_at->diffForHumans() }}</td>
                                        <td>{{ $cliente->updated_at->diffForHumans() }}</td>
                                        <td>                                            
                                            <a href="{{ route('crm.clients.show', $cliente->id) }}" title="Ficha">
                                                <i class="material-icons">account_circle</i>
                                            </a>
                                            <a href="{{ route('crm.clients.edit', $cliente->id) }}" title="Editar">
                                                <i class="material-icons">mode_edit</i>
                                            </a>                                            
                                            <a href="{{ route('crm.clients.delete', $cliente->id) }}" class="btn-request-post" title="Eliminar">
                                                <i class="material-icons">delete_forever</i>
                                            </a>

                                            @if($cliente->estado->slug === Constants::NAME_ESTADO_CLIENTE_SUSPENDIDO)
                                                <a href="{{ route('crm.clients.suspend', $cliente->id) }}" class="btn-request-post" title="Suspender">
                                                    <i class="material-icons">visibility_off</i>
                                                </a>
                                            @else
                                                <a href="{{ route('crm.clients.activate', $cliente->id) }}" class="btn-request-post" title="Activar">                                                    
                                                    <i class="material-icons">restore</i>
                                                </a>
                                            @endif

                                            <a href="{{ route('crm.clients.contact', $cliente->id) }}" class="btn-contact-modal" title="Contactar">
                                                <i class="material-icons">speaker_notes</i>
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')

	@parent
	<!-- Jquery DataTable Plugin Js -->
    <script src="{{ asset('assets/admin/plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('assets/admin/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('assets/admin/js/pages/tables/jquery-datatable.js') }}"></script>
    
@endsection