routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

Route::middleware(['auth', 'checkUserSession'])->prefix('administracion')->group(function() {
    
    Route::prefix('/')->name('home.')->group(function () {

        Route::get('/', 'Admin\HomeController@index')->name('index');

        Route::get('profile', 'Admin\HomeController@profile')->name('profile');

        Route::post('profile', 'Admin\HomeController@updateProfile')->name('update-profile');

        Route::post('cancel', 'Admin\HomeController@cancel')->name('cancel');
    });

    Route::prefix('crm')->name('crm.')->group(function () {

        Route::prefix('facturas')->name('invoices.')->group(function () {

            Route::get('/', 'Admin\FacturasController@index')->middleware(['role:superadministrador|administrador'])->name('index');

            Route::get('{id}/detalle', 'Admin\FacturasController@show')->middleware(['role:superadministrador|administrador|vendedor'])->name('show');

            Route::get('{id}/editar', 'Admin\FacturasController@edit')->middleware(['role:superadministrador|administrador'])->name('edit');

            Route::post('{id}/editar', 'Admin\FacturasController@update')->middleware(['role:superadministrador|administrador'])->name('update');

            Route::post('{id}/aprobar', 'Admin\FacturasController@approve')->middleware(['role:superadministrador|administrador'])->name('approve');

            Route::post('{id}/anular', 'Admin\FacturasController@cancel')->middleware(['role:superadministrador|administrador'])->name('cancel');
        });

        Route::prefix('clientes')->middleware(['role:superadministrador|administrador'])->name('clients.')->group(function () {

            Route::get('/', 'Admin\ClientesController@index')->name('index');

            Route::get('pendientes', 'Admin\ClientesController@indexPending')->name('index-pending');

            Route::get('nuevo', 'Admin\ClientesController@create')->name('create');

            Route::post('nuevo', 'Admin\ClientesController@store')->name('store');

            Route::get('{id}/ficha', 'Admin\ClientesController@show')->name('show');

            Route::get('{id}/editar', 'Admin\ClientesController@edit')->name('edit');

            Route::post('{id}/editar', 'Admin\ClientesController@update')->name('update');

            Route::post('{id}/eliminar', 'Admin\ClientesController@delete')->name('delete');

            Route::post('{id}/activar', 'Admin\ClientesController@activate')->name('activate');

            Route::post('{id}/suspender', 'Admin\ClientesController@suspend')->name('suspend');

            Route::post('{id}/anular', 'Admin\ClientesController@cancel')->name('cancel');

            Route::post('{id}/contactar', 'Admin\ClientesController@contact')->name('contact');

            Route::prefix('{id}/evaluaciones')->middleware(['role:superadministrador|administrador'])->name('evaluations.')->group(function () {

                Route::prefix('entrenamientos')->middleware(['role:superadministrador|administrador'])->name('trainers.')->group(function () {

                    Route::get('/', 'Admin\EvaluacionesController@trainers')->name('index');

                    Route::get('nuevo', 'Admin\EvaluacionesController@createTrainers')->name('create');

                    Route::post('nuevo', 'Admin\EvaluacionesController@storeTrainers')->name('store');

                    Route::get('{evaluation}/editar', 'Admin\EvaluacionesController@editTrainers')->name('edit');

                    Route::post('{evaluation}/editar', 'Admin\EvaluacionesController@updateTrainers')->name('update');

                    Route::post('{evaluation}/eliminar', 'Admin\EvaluacionesController@deleteTrainers')->name('delete');
                });

                Route::prefix('nutricionistas')->middleware(['role:superadministrador|administrador'])->name('nutritionists.')->group(function () {
    
                    Route::get('/', 'Admin\EvaluacionesController@nutritionist')->name('index');

                    Route::get('nuevo', 'Admin\EvaluacionesController@createNutritionist')->name('create');

                    Route::post('nuevo', 'Admin\EvaluacionesController@storeNutritionist')->name('store');

                    Route::get('{evaluation}/editar', 'Admin\EvaluacionesController@editNutritionist')->name('edit');

                    Route::post('{evaluation}/editar', 'Admin\EvaluacionesController@updateNutritionist')->name('update');

                    Route::post('{evaluation}/eliminar', 'Admin\EvaluacionesController@deleteNutritionist')->name('delete');
                });

                Route::prefix('{evaluation}/items')->middleware(['role:superadministrador|administrador'])->name('items.')->group(function () {

                    Route::post('{item}/editar', 'Admin\EvaluacionesController@updateItem')->name('update');

                    Route::post('{item}/eliminar', 'Admin\EvaluacionesController@deleteItem')->name('delete');
                });
            });
        });

        Route::prefix('entrenadores')->middleware(['role:superadministrador|administrador'])->name('trainers.')->group(function () {

            Route::get('/', 'Admin\EntrenadoresController@index')->name('index');

            Route::get('nuevo', 'Admin\EntrenadoresController@create')->name('create');

            Route::post('nuevo', 'Admin\EntrenadoresController@store')->name('store');

            Route::get('{id}/detalle', 'Admin\EntrenadoresController@detail')->name('detail');

            Route::get('{id}/editar', 'Admin\EntrenadoresController@edit')->name('edit');

            Route::post('{id}/editar', 'Admin\EntrenadoresController@update')->name('update');

            Route::post('{id}/eliminar', 'Admin\EntrenadoresController@delete')->name('delete');

            Route::post('{id}/activar', 'Admin\EntrenadoresController@activate')->name('activate');

            Route::post('{id}/suspender', 'Admin\EntrenadoresController@suspend')->name('suspend');

            Route::post('{id}/anular', 'Admin\EntrenadoresController@cancel')->name('cancel');
        });

        Route::prefix('nutricionistas')->middleware(['role:superadministrador|administrador'])->name('nutritionists.')->group(function () {

            Route::get('/', 'Admin\NutricionistasController@index')->name('index');

            Route::get('nuevo', 'Admin\NutricionistasController@create')->name('create');

            Route::post('nuevo', 'Admin\NutricionistasController@store')->name('store');

            Route::get('{id}/detalle', 'Admin\NutricionistasController@detail')->name('detail');

            Route::get('{id}/editar', 'Admin\NutricionistasController@edit')->name('edit');

            Route::post('{id}/editar', 'Admin\NutricionistasController@update')->name('update');

            Route::post('{id}/eliminar', 'Admin\NutricionistasController@delete')->name('delete');

            Route::post('{id}/activar', 'Admin\NutricionistasController@activate')->name('activate');

            Route::post('{id}/suspender', 'Admin\NutricionistasController@suspend')->name('suspend');

            Route::post('{id}/anular', 'Admin\NutricionistasController@cancel')->name('cancel');
        });

        /*Route::prefix('informes')->middleware(['role:superadministrador|administrador'])->name('reports.')->group(function () {

            Route::get('/', 'Admin\InformesController@index')->name('index');

            Route::get('proccess', 'Admin\InformesController@proccess')->name('proccess');
        });*/
    });

    Route::prefix('configuracion')->name('configuration.')->group(function () {

        Route::prefix('planes')->middleware(['role:superadministrador|administrador'])->name('plans.')->group(function () {

            Route::get('/', 'Admin\PlanesController@index')->name('index');

            Route::get('nuevo', 'Admin\PlanesController@create')->name('create');

            Route::post('nuevo', 'Admin\PlanesController@store')->name('store');

            Route::get('{id}/editar', 'Admin\PlanesController@edit')->name('edit');

            Route::post('{id}/editar', 'Admin\PlanesController@update')->name('update');

            Route::post('{id}/eliminar', 'Admin\PlanesController@delete')->name('delete');

            Route::post('{id}/suspender', 'Admin\PlanesController@suspend')->name('suspend');

            Route::post('{id}/activar', 'Admin\PlanesController@activate')->name('activate');
        });

        Route::prefix('usuarios')->middleware(['role:superadministrador|administrador'])->name('users.')->group(function () {

            Route::get('/', 'Admin\UsuariosController@index')->name('index');

            Route::get('nuevo', 'Admin\UsuariosController@create')->name('create');

            Route::post('nuevo', 'Admin\UsuariosController@store')->name('store');

            Route::get('{id}/editar', 'Admin\UsuariosController@edit')->name('edit');

            Route::post('{id}/editar', 'Admin\UsuariosController@update')->name('update');

            Route::post('{id}/eliminar', 'Admin\UsuariosController@delete')->name('delete');

            Route::post('{id}/suspender', 'Admin\UsuariosController@suspend')->name('suspend');

            Route::post('{id}/activar', 'Admin\UsuariosController@activate')->name('activate');
        });        
    });
});

resources/views/admin/template/header.blade.php
<nav class="navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a>
            <a href="javascript:void(0);" class="bars"></a>
            <a class="navbar-brand" href="{{ route('home.index') }}">Löwin | Fit & Nut</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <!-- Notifications -->
                <li class="dropdown">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button">
                        <i class="material-icons">notifications</i>
                        <span class="label-count">7</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">NOTIFICACIONES</li>
                        <li class="body">
                            <ul class="menu">
								<li>
                                    <a href="javascript:void(0);">
                                        <div class="icon-circle bg-blue-grey">
                                            <i class="material-icons">comment</i>
                                        </div>
                                        <div class="menu-info">
                                            <h4><b>John</b> Consulta tecnica</h4>
                                            <p>
                                                <i class="material-icons">access_time</i> 4 hours ago
                                            </p>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        <div class="icon-circle bg-light-green">
                                            <i class="material-icons">person_add</i>
                                        </div>
                                        <div class="menu-info">
                                            <h4>12 Nuevos usuarios</h4>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        <div class="icon-circle bg-cyan">
                                            <i class="material-icons">add_shopping_cart</i>
                                        </div>
                                        <div class="menu-info">
                                            <h4>4 Ventas</h4>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="footer">
                            <a href="#">Ver todas las consultas</a>
                        </li>
                    </ul>
                </li>
                <!-- #END# Notifications -->
                <!-- Tasks -->
                <li class="dropdown">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button">
                        <i class="material-icons">feedback</i>
                        <span class="label-count">9</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">Contacto</li>
                        <li class="body">
                            <ul class="menu tasks">
                                <li>
                                    <a href="javascript:void(0);">
                                        <h4>
                                            Contacto Entrenador
                                            <small>50%</small>
                                        </h4>
                                        <div class="progress">
                                            <div class="progress-bar bg-pink" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width: 50%">
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:void(0);">
                                        <h4>
                                            Contacto Nutricionista
                                            <small>50%</small>
                                        </h4>
                                        <div class="progress">
                                            <div class="progress-bar bg-cyan" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width: 50%">
                                            </div>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </li>
						<li class="footer">
							<a href="#">Estadisticas del último mes</a>
						</li>
                    </ul>
                </li>
                <!-- #END# Tasks -->
                <li class="pull-right"><a href="javascript:void(0);" class="js-right-sidebar" data-close="true"><i class="material-icons">settings</i></a></li>
            </ul>
        </div>
    </div>
</nav>

resources/views/admin/template/modals.blade.php
<div class="content-modals">    
    <div class="modal fade" id="contact-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            {!! Form::open(['id' => 'contact-modal-form', 'method' => 'POST', 'files' => true]) !!}
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="defaultModalLabel">Contactar Cliente</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="margin-top: -25px; font-size: 28px;">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="row clearfix">
                            <div class="col-xs-12">
                                <div class="form-group form-float">
                                    <label class="form-label">Asunto (Opcional)</label>
                                    <input type="text" class="form-control" name="asunto">
                                </div>
                            </div>
                            <div class="col-xs-12">
                                <div class="form-group form-float">
                                    <label class="form-label">Mensaje</label>
                                    <textarea name="mensaje" class="form-control no-resize" rows="4" required="required"></textarea>                                
                                </div>
                            </div>
                            <div class="col-xs-12">
                                <div class="form-group form-float">
                                    <label class="form-label">Adjuntar archivo (Opcional)</label>
                                    <input type="file" class="form-control" name="file">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">                        
                        <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">CANCELAR</button>
                        <button type="submit" class="btn btn-link waves-effect">ENVIAR</button>
                    </div>
                </div>                    
            {!! Form::close() !!}
        </div>
    </div>
</div>

resources/views/admin/template/sidebar.blade.php
<section>
    <!-- Left Sidebar -->
    <aside id="leftsidebar" class="sidebar">
        <!-- User Info -->
        <div class="user-info">
            <div class="info-container">
                <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><h3>{{ auth()->user()->name }}</h3></div>
                <div class="email">{{ auth()->user()->email }}</div>
                <div class="btn-group user-helper-dropdown">
                    <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
                    <ul class="dropdown-menu pull-right">
                        <li><a href="javascript:void(0);"><i class="material-icons">person</i>Perfil</a></li>
                        <li role="seperator" class="divider"></li>
                        <li><a href="javascript:void(0);"><i class="material-icons">group</i>Mis Coach</a></li>
                        <li><a href="javascript:void(0);"><i class="material-icons">shopping_cart</i>Mi plan</a></li>
                        <li role="seperator" class="divider"></li>
                        <li>
                            <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                <i class="material-icons">input</i>
                                Salir
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- #User Info -->
        <!-- Menu -->
        <div class="menu">
            @role([Constants::NAME_ROLE_SUPERADMINISTRADOR, Constants::NAME_ROLE_ADMINISTRADOR])
                <ul class="list">
                    <li class="header">MENU PRINCIPAL</li>
                    <li class="{{ Ekko::isActiveRoute(['home.index'], 'active') }}">
                        <a href="{{ route('home.index') }}">
                            <i class="material-icons col-red">home</i>
                            <span>Dashboard</span>
                        </a>
                    </li>
                    <li class="{{ Ekko::areActiveRoutes(['crm.clients.*'], 'active') }}">
                        <a href="{{ route('crm.clients.index') }}">
                            <i class="material-icons col-red">work</i>
                            <span>Clientes</span>
                        </a>
                    </li>
                    <li class="{{ Ekko::areActiveRoutes(['crm.trainers.*'], 'active') }}">
                        <a href="{{ route('crm.trainers.index') }}">
                            <i class="material-icons col-red">fitness_center</i>
                            <span>Entrenadores</span>
                        </a>
                    </li>
                    <li class="{{ Ekko::areActiveRoutes(['crm.nutritionists.*'], 'active') }}">
                        <a href="{{ route('crm.nutritionists.index') }}">
                            <i class="material-icons col-red">assignment_ind</i>
                            <span>Nutricionistas</span>
                        </a>
                    </li>
                    <li class="{{ Ekko::areActiveRoutes(['crm.invoices.*'], 'active') }}">
                        <a href="{{ route('crm.invoices.index') }}">
                            <i class="material-icons col-red">insert_drive_file</i>
                            <span>Facturas</span>
                        </a>
                    </li>                    
                    <li class="{{ Ekko::areActiveRoutes(['configuration.plans.*'], 'active') }}">
                        <a href="{{ route('configuration.plans.index') }}">
                            <i class="material-icons col-red">card_membership</i>
                            <span>Planes</span>
                        </a>
                    </li>
                    <li class="{{ Ekko::areActiveRoutes(['configuration.users.*'], 'active') }}">
                        <a href="{{ route('configuration.users.index') }}">
                            <i class="material-icons col-red">supervisor_account</i>
                            <span>Usuarios</span>
                        </a>
                    </li>
                    <li style="display: none;">
                        <a href="javascript:void(0);" class="menu-toggle">
                            <i class="material-icons col-red">settings</i>
                            <span>Configuración</span>
                        </a>
                        <ul class="ml-menu">                        
                        </ul>
                    </li>
                    <li>
                        <a href="#">
                            <i class="material-icons col-light-blue">announcement</i>
                            <span>Solicitar Ayuda</span>
                        </a>
                    </li>
                </ul>
            @endrole

            @role(Constants::NAME_ROLE_CLIENTE)
                <ul class="list">
                    <li class="header">MAIN NAVIGATION</li>
                    <li class="active">
                        <a href="index.html">
                            <i class="material-icons">trending_up</i>
                            <span>Mis Estadísticas</span>
                        </a>
                    </li>
                    <li>
                        <a href="ficha.html">
                            <i class="material-icons col-red">favorite</i>
                            <span>Mi Ficha</span>
                        </a>
                    </li>
                    <li>
                        <a href="entrenamiento.html">
                            <i class="material-icons col-red">fitness_center</i>
                            <span>Mi Entrenamiento</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="material-icons col-red">kitchen</i>
                            <span>Mi Plan Nutricional</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="material-icons col-green">spa</i>
                            <span>Bienestar</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="material-icons col-green">wb_incandescent</i>
                            <span>Tips</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="material-icons col-green">card_giftcard</i>
                            <span>Mis Gift Card</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="material-icons col-light-blue">announcement</i>
                            <span>Solicitar Ayuda</span>
                        </a>
                    </li>
                </ul>
            @endrole
        </div>
        <!-- #Menu -->
        <!-- Footer -->
        <div class="legal">
            <div class="copyright">
                &copy; 2020 - 2021&nbsp;<a href="{{ route('home.index') }}">Löwin | Fit & Nut</a>
            </div>
            <div class="version">
                <b>Version:&nbsp;</b>&nbsp;{{ Constants::VERSION_SYSTEM }}
            </div>
        </div>
        <!-- #Footer -->
    </aside>
    <!-- #END# Left Sidebar -->
    <!-- Right Sidebar -->
    <aside id="rightsidebar" class="right-sidebar">
        <div>
            <div class="fade in active in active" id="settings">
                <div class="demo-settings">
                    <p>NOTIFICACIONES</p>
                    <ul class="setting-list">
						<li>
                            <span>Notificame por Email</span>
                            <div class="switch">
                                <label><input type="checkbox" checked><span class="lever"></span></label>
                            </div>
                        </li>
                        <li>
                            <span>Respuestas</span>
                            <div class="switch">
                                <label><input type="checkbox" checked><span class="lever"></span></label>
                            </div>
                        </li>
                        <li>
                            <span>Preguntas</span>
                            <div class="switch">
                                <label><input type="checkbox"><span class="lever"></span></label>
                            </div>
                        </li>
						<li>
                            <span>Nuevo Contenidos</span>
                            <div class="switch">
                                <label><input type="checkbox"><span class="lever"></span></label>
                            </div>
                        </li>
						<li>
                            <span>Termino Plan</span>
                            <div class="switch">
                                <label><input type="checkbox"><span class="lever"></span></label>
                            </div>
                        </li>
                    </ul>
                    <p>RECORDATORIOS</p>
                    <ul class="setting-list">
                        <li>
                            <span>Recordatorios por Email</span>
                            <div class="switch">
                                <label><input type="checkbox" checked><span class="lever"></span></label>
                            </div>
                        </li>
                        <li>
                            <span>Entrenamiento</span>
                            <div class="switch">
                                <label><input type="checkbox" checked><span class="lever"></span></label>
                            </div>
                        </li>
                        <li>
                            <span>Evaluación</span>
                            <div class="switch">
                                <label><input type="checkbox" checked><span class="lever"></span></label>
                            </div>
                        </li>
						<li>
                            <span>Renovación de plan</span>
                            <div class="switch">
                                <label><input type="checkbox"><span class="lever"></span></label>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </aside>
    <!-- #END# Right Sidebar -->
</section>