routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

Route::middleware(['auth', 'checkUserSession'])->prefix('administracion')->group(function() {
    
    Route::prefix('/')->name('home.')->group(function () {

        Route::get('/', 'Admin\HomeController@index')->name('index');

        Route::get('profile', 'Admin\HomeController@profile')->name('profile');

        Route::post('profile', 'Admin\HomeController@updateProfile')->name('update-profile');

        Route::post('cancel', 'Admin\HomeController@cancel')->name('cancel');
    });

    Route::prefix('crm')->name('crm.')->group(function () {

        Route::prefix('facturas')->name('invoices.')->group(function () {

            Route::get('/', 'Admin\FacturasController@index')->middleware(['role:superadministrador|administrador'])->name('index');

            Route::get('{id}/detalle', 'Admin\FacturasController@show')->middleware(['role:superadministrador|administrador|vendedor'])->name('show');

            Route::get('{id}/editar', 'Admin\FacturasController@edit')->middleware(['role:superadministrador|administrador'])->name('edit');

            Route::post('{id}/editar', 'Admin\FacturasController@update')->middleware(['role:superadministrador|administrador'])->name('update');

            Route::post('{id}/aprobar', 'Admin\FacturasController@approve')->middleware(['role:superadministrador|administrador'])->name('approve');

            Route::post('{id}/anular', 'Admin\FacturasController@cancel')->middleware(['role:superadministrador|administrador'])->name('cancel');
        });

        Route::prefix('clientes')->middleware(['role:superadministrador|administrador'])->name('clients.')->group(function () {

            Route::get('/', 'Admin\ClientesController@index')->name('index');

            Route::get('pendientes', 'Admin\ClientesController@indexPending')->name('index-pending');

            Route::get('nuevo', 'Admin\ClientesController@create')->name('create');

            Route::post('nuevo', 'Admin\ClientesController@store')->name('store');

            Route::get('{id}/ficha', 'Admin\ClientesController@show')->name('show');

            Route::get('{id}/editar', 'Admin\ClientesController@edit')->name('edit');

            Route::post('{id}/editar', 'Admin\ClientesController@update')->name('update');

            Route::post('{id}/eliminar', 'Admin\ClientesController@delete')->name('delete');

            Route::post('{id}/activar', 'Admin\ClientesController@activate')->name('activate');

            Route::post('{id}/suspender', 'Admin\ClientesController@suspend')->name('suspend');

            Route::post('{id}/anular', 'Admin\ClientesController@cancel')->name('cancel');

            Route::post('{id}/contactar', 'Admin\ClientesController@contact')->name('contact');

            Route::prefix('{id}/evaluaciones')->middleware(['role:superadministrador|administrador'])->name('evaluations.')->group(function () {

                Route::prefix('entrenamientos')->middleware(['role:superadministrador|administrador'])->name('trainers.')->group(function () {

                    Route::get('/', 'Admin\EvaluacionesController@trainers')->name('index');

                    Route::get('nuevo', 'Admin\EvaluacionesController@createTrainers')->name('create');

                    Route::post('nuevo', 'Admin\EvaluacionesController@storeTrainers')->name('store');

                    Route::get('{evaluation}/editar', 'Admin\EvaluacionesController@editTrainers')->name('edit');

                    Route::post('{evaluation}/editar', 'Admin\EvaluacionesController@updateTrainers')->name('update');

                    Route::post('{evaluation}/eliminar', 'Admin\EvaluacionesController@deleteTrainers')->name('delete');
                });

                Route::prefix('nutricionistas')->middleware(['role:superadministrador|administrador'])->name('nutritionists.')->group(function () {
    
                    Route::get('/', 'Admin\EvaluacionesController@nutritionist')->name('index');

                    Route::get('nuevo', 'Admin\EvaluacionesController@createNutritionist')->name('create');

                    Route::post('nuevo', 'Admin\EvaluacionesController@storeNutritionist')->name('store');

                    Route::get('{evaluation}/editar', 'Admin\EvaluacionesController@editNutritionist')->name('edit');

                    Route::post('{evaluation}/editar', 'Admin\EvaluacionesController@updateNutritionist')->name('update');

                    Route::post('{evaluation}/eliminar', 'Admin\EvaluacionesController@deleteNutritionist')->name('delete');
                });

                Route::prefix('{evaluation}/items')->middleware(['role:superadministrador|administrador'])->name('items.')->group(function () {

                    Route::post('{item}/editar', 'Admin\EvaluacionesController@updateItem')->name('update');

                    Route::post('{item}/eliminar', 'Admin\EvaluacionesController@deleteItem')->name('delete');
                });
            });
        });

        Route::prefix('entrenadores')->middleware(['role:superadministrador|administrador'])->name('trainers.')->group(function () {

            Route::get('/', 'Admin\EntrenadoresController@index')->name('index');

            Route::get('nuevo', 'Admin\EntrenadoresController@create')->name('create');

            Route::post('nuevo', 'Admin\EntrenadoresController@store')->name('store');

            Route::get('{id}/detalle', 'Admin\EntrenadoresController@detail')->name('detail');

            Route::get('{id}/editar', 'Admin\EntrenadoresController@edit')->name('edit');

            Route::post('{id}/editar', 'Admin\EntrenadoresController@update')->name('update');

            Route::post('{id}/eliminar', 'Admin\EntrenadoresController@delete')->name('delete');

            Route::post('{id}/activar', 'Admin\EntrenadoresController@activate')->name('activate');

            Route::post('{id}/suspender', 'Admin\EntrenadoresController@suspend')->name('suspend');

            Route::post('{id}/anular', 'Admin\EntrenadoresController@cancel')->name('cancel');
        });

        Route::prefix('nutricionistas')->middleware(['role:superadministrador|administrador'])->name('nutritionists.')->group(function () {

            Route::get('/', 'Admin\NutricionistasController@index')->name('index');

            Route::get('nuevo', 'Admin\NutricionistasController@create')->name('create');

            Route::post('nuevo', 'Admin\NutricionistasController@store')->name('store');

            Route::get('{id}/detalle', 'Admin\NutricionistasController@detail')->name('detail');

            Route::get('{id}/editar', 'Admin\NutricionistasController@edit')->name('edit');

            Route::post('{id}/editar', 'Admin\NutricionistasController@update')->name('update');

            Route::post('{id}/eliminar', 'Admin\NutricionistasController@delete')->name('delete');

            Route::post('{id}/activar', 'Admin\NutricionistasController@activate')->name('activate');

            Route::post('{id}/suspender', 'Admin\NutricionistasController@suspend')->name('suspend');

            Route::post('{id}/anular', 'Admin\NutricionistasController@cancel')->name('cancel');
        });

        /*Route::prefix('informes')->middleware(['role:superadministrador|administrador'])->name('reports.')->group(function () {

            Route::get('/', 'Admin\InformesController@index')->name('index');

            Route::get('proccess', 'Admin\InformesController@proccess')->name('proccess');
        });*/
    });

    Route::prefix('configuracion')->name('configuration.')->group(function () {

        Route::prefix('planes')->middleware(['role:superadministrador|administrador'])->name('plans.')->group(function () {

            Route::get('/', 'Admin\PlanesController@index')->name('index');

            Route::get('nuevo', 'Admin\PlanesController@create')->name('create');

            Route::post('nuevo', 'Admin\PlanesController@store')->name('store');

            Route::get('{id}/editar', 'Admin\PlanesController@edit')->name('edit');

            Route::post('{id}/editar', 'Admin\PlanesController@update')->name('update');

            Route::post('{id}/eliminar', 'Admin\PlanesController@delete')->name('delete');

            Route::post('{id}/suspender', 'Admin\PlanesController@suspend')->name('suspend');

            Route::post('{id}/activar', 'Admin\PlanesController@activate')->name('activate');
        });

        Route::prefix('usuarios')->middleware(['role:superadministrador|administrador'])->name('users.')->group(function () {

            Route::get('/', 'Admin\UsuariosController@index')->name('index');

            Route::get('nuevo', 'Admin\UsuariosController@create')->name('create');

            Route::post('nuevo', 'Admin\UsuariosController@store')->name('store');

            Route::get('{id}/editar', 'Admin\UsuariosController@edit')->name('edit');

            Route::post('{id}/editar', 'Admin\UsuariosController@update')->name('update');

            Route::post('{id}/eliminar', 'Admin\UsuariosController@delete')->name('delete');

            Route::post('{id}/suspender', 'Admin\UsuariosController@suspend')->name('suspend');

            Route::post('{id}/activar', 'Admin\UsuariosController@activate')->name('activate');
        });        
    });
});

app/Http/Controllers/Admin/EvaluacionesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Globals\Alerts;
use App\Http\Controllers\Controller;
use App\Http\Requests\CreateEvaluationNutritionistRequest;
use App\Http\Requests\CreateEvaluationTrainerRequest;
use App\Http\Requests\EditEvaluationTrainerRequest;
use App\Repositories\Clientes\ClientesRepoI;
use App\Repositories\Evaluaciones\EvaluacionesRepoI;
use Illuminate\Http\Request;

class EvaluacionesController extends Controller
{
    protected $clientesRepo, $evaluacionesRepo;

    public function __construct(ClientesRepoI $clientesRepo, EvaluacionesRepoI $evaluacionesRepo)
    {
        $this->clientesRepo = $clientesRepo;
        $this->evaluacionesRepo = $evaluacionesRepo;
    }

    public function trainers($clientId)
    {
        $cliente = $this->clientesRepo->with(['evaluacionesCliente', 'evaluacionesCliente.itemsEvaluacion'])->findOneBy(['id' => $clientId]);

        return view('admin.crm.evaluaciones.entrenamientos.index', [
            'cliente' => $cliente
        ]);
    }

    public function createTrainers($clientId)
    {
        $codigo = $this->evaluacionesRepo->getUniqueEvaluationCode();
        $cliente = $this->clientesRepo->findOneBy(['id' => $clientId]);

        return view('admin.crm.evaluaciones.entrenamientos.create', [
            'cliente' => $cliente,
            'codigo'  => $codigo
        ]);
    }

    public function storeTrainers($clientId, CreateEvaluationTrainerRequest $request)
    {
        $data = $request->except(['_token', 'questions', 'answers']);
        $dataItems = [];

        $data['cliente_id'] = $clientId;
        $data['fecha'] = date('Y-m-d', strtotime($data['fecha']));

        /** Set Data Evaluation Items */
        foreach ($request->post('questions') as $key => $question) {
            $dataItems[] = [
                'orden'     => ($key + 1),
                'pregunta'  => $question,
                'respuesta' => $request->post('answers')[$key]
            ];
        }

        $this->evaluacionesRepo->createEvaluationTrainers($data, $dataItems);

        return redirect()->route('crm.clients.evaluations.trainers.index', $clientId)   
            ->with('message', Alerts::CREATE_SUCCESS)
            ->with('messageType', 'success');        
    }

    public function editTrainers($clientId, $id)
    {
        $evaluacion = $this->evaluacionesRepo->with(['cliente', 'itemsEvaluacion'])->findOneBy(['id' => $id]);

        return view('admin.crm.evaluaciones.entrenamientos.edit', [
            'evaluacion' => $evaluacion,
        ]);
    }

    public function updateTrainers($clientId, $id, EditEvaluationTrainerRequest $request)
    {
        $data = $request->except(['_token', 'codigo', 'questions', 'answers']);
        $data['fecha'] = date('Y-m-d', strtotime($data['fecha']));

        $this->evaluacionesRepo->updateBy(['id' => $id], $data);

        return redirect()->route('crm.clients.evaluations.trainers.index', $clientId)
            ->with('message', Alerts::UPDATE_SUCCESS)
            ->with('messageType', 'success');
    }

    public function deleteTrainers($clientId, $id, Request $request)
    {
        //$this->evaluacionesRepo->createEvaluationTrainers($data, $dataItems);

        return redirect()->route('crm.clients.evaluations.trainers.index', $clientId)
            ->with('message', Alerts::DELETE_SUCCESS)
            ->with('messageType', 'success');
    }

    public function nutritionist($clientId)
    {
        $cliente = $this->clientesRepo->findOneBy(['id' => $clientId]);

        return view('admin.crm.evaluaciones.nutricionistas.index', [
            'cliente' => $cliente
        ]);
    }

    public function storeNutritionists($clientId, CreateEvaluationNutritionistRequest $request)
    {
        $data = $request->except(['_token', 'questions', 'answers']);
        $dataItems = [];

        $data['cliente_id'] = $clientId;
        $data['fecha'] = date('Y-m-d', strtotime($data['fecha']));

        /** Set Data Evaluation Items */
        foreach ($request->post('questions') as $key => $question) {
            $dataItems[] = [
                'orden'     => ($key + 1),
                'pregunta'  => $question,
                'respuesta' => $request->post('answers')[$key]
            ];
        }

        $this->evaluacionesRepo->createEvaluationTrainers($data, $dataItems);

        return redirect()->route('crm.clients.evaluations.trainers.index', $clientId)
            ->with('message', Alerts::CREATE_SUCCESS)
            ->with('messageType', 'success');
    }

    public function updateItem($clientId, $evaluacionId, $id, Request $request)
    {
        return response()->json(true);
    }
}

resources/views/admin/crm/evaluaciones/entrenamientos/create.blade.php
@extends('admin.template.base')

@section('styles')

    @parent
    <!-- Bootstrap Material Datetime Picker Css -->
    <link href="{{ asset('assets/admin/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css') }}" rel="stylesheet" />
    <!--WaitMe Css-->
    <link href="{{ asset('assets/admin/plugins/waitme/waitMe.css') }}" rel="stylesheet" />

    <style>
        .card-items-evaluation > .body {
            max-height: 100vh;
            overflow-y: scroll;
        }
        .card.card-question {
            margin-bottom: 20px !important;
        }
        .card.card-question .btn-delete-question {
            cursor: pointer;
        }
        .card-question .form-group {
            margin-bottom: 0 !important;
        }
    </style>

@endsection

@section('content')

    @include('admin.errors.errors')

    <div class="row clearfix">
        <div class="col-xs-12">
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('home.index') }}">
                        <i class="material-icons">home</i>&nbsp;Inicio
                    </a>
                </li>
                <li>
                    <a href="{{ route('crm.clients.index') }}">
                        <i class="material-icons">work</i>&nbsp;Clientes
                    </a>
                </li>
                <li>
                    <a href="{{ route('crm.clients.show', $cliente->id) }}">
                        {{ $cliente->getFullName() }}
                    </a>
                </li>
                <li>
                    <a href="{{ route('crm.clients.evaluations.trainers.index', $cliente->id) }}">
                        Evaluaciones Entrenamientos
                    </a>
                </li>
                <li class="active">
                    Nuevo
                </li>
            </ol>
        </div>
    </div>

    {!! Form::open(['id' => 'form-create-trainer-evaluation', 'url' => route('crm.clients.evaluations.trainers.store', $cliente->id), 'method' => 'POST']) !!}
        <div class="row clearfix">
            <div class="col-md-6 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>DATOS INFORMATIVOS</h2>
                    </div>
                    <div class="body">
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <label class="form-label">Código</label>
                                        <input type="text" class="form-control" name="codigo" value="{{ $codigo }}" required="required" readonly="readonly">
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-12">
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="text" class="form-control datepicker" name="fecha" value="{{ old('fecha') }}" placeholder="Fecha" required="required" tabindex="1">
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-12">
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <label class="form-label">Estado</label>
                                        <select name="estado" class="form-control" required="required" tabindex="2">
                                            <option value="{{ Constants::CODE_ESTADO_EVALUACION_PENDIENTE }}" {{ (old('estado') === Constants::CODE_ESTADO_EVALUACION_PENDIENTE) ? 'selected' : null }}>Pendiente</option>
                                            <option value="{{ Constants::CODE_ESTADO_EVALUACION_COMPLETADO }}" {{ (old('estado') === Constants::CODE_ESTADO_EVALUACION_COMPLETADO) ? 'selected' : null }}>Completado</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <button class="btn btn-primary waves-effect pull-right" type="submit">Guardar</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-sm-12 col-xs-12">
                <div class="card card-items-evaluation">
                    <div class="header clearfix">
                        <div class="pull-left">
                            <h2 style="margin-top: 10px;">ITEMS DE EVALUACIÓN</h2>
                        </div>
                        <div class="pull-right">
                            <a class="btn btn-sm btn-info btn-add-question">
                                <i class="material-icons">add</i>
                            </a>
                        </div>
                    </div>
                    <div class="body">
                        <div class="row clearfix">
                            <div class="col-xs-12">
                                <div class="box-evaluation-questions"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {!! Form::close() !!}

@endsection

@section('scripts')

	@parent
	<!-- Jquery Validation Plugin Css -->
    <script src="{{ asset('assets/admin/plugins/jquery-validation/jquery.validate.js') }}"></script>
    <!-- Moment Plugin Js -->
    <script src="{{ asset('assets/admin/plugins/momentjs/moment-with-locale.js') }}"></script>
    <!-- Bootstrap Material Datetime Picker Plugin Js -->
    <script src="{{ asset('assets/admin/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js') }}"></script>
    <!-- Wait Me Plugin Js -->
    <script src="{{ asset('assets/admin/plugins/waitme/waitMe.js') }}"></script>
    <script src="{{ asset('assets/admin/js/pages/cards/basic.js') }}"></script>
    <script>
        $(function () {

            $('#form-create-trainer-evaluation').validate({
                rules: {
                    codigo: "required",
                    fecha: "required",
                    estado: "required",
                },
                highlight: function (input) {
                    $(input).parents('.form-line').addClass('error');
                },
                unhighlight: function (input) {
                    $(input).parents('.form-line').removeClass('error');
                },
                errorPlacement: function (error, element) {
                    $(element).parents('.form-group').append(error);
                }
            });

            $('.datepicker').bootstrapMaterialDatePicker({
                format: 'DD-MM-YYYY',
                lang : 'es',
                cancelText: 'Cancelar',
                clearText: 'Limpiar',
                clearButton: true,
                weekStart: 1,
                time: false
            });

            $(document).on('click', '.btn-add-question', function(event) {
                event.preventDefault();
                $('.box-evaluation-questions').append(makeEvaluationQuestionHTML());
            });

            $(document).on('click', '.btn-delete-question', function(event) {
                event.preventDefault();
                $(this).parents('.card-question').remove();
            });

            function makeEvaluationQuestionHTML()
            {
                var html = '';

                html += '<div class="card card-question">';
                html += '    <div class="header">';
                html += '        <h5 class="m-b-20">Escriba una Pregunta ....</h5>';
                html += '        <div class="form-group form-float">';
                html += '            <div class="form-line">';
                html += '                <input type="text" name="questions[]" class="form-control" placeholder="¿Cuantas Calorias ... ?">';
                html += '            </div>';
                html += '        </div>';
                html += '        <ul class="header-dropdown m-r--5">';
                html += '            <li>';
                html += '                <a class="btn-delete-question" title="Eliminar Item">';
                html += '                    <i class="material-icons">delete</i>';
                html += '                </a>';
                html += '            </li>';
                html += '        </ul>';
                html += '    </div>';
                html += '    <div class="body">';
                html += '        <div class="form-group form-float">';
                html += '            <div class="form-line">';
                html += '                <textarea name="answers[]" class="form-control no-resize" placeholder="Escriba una respuesta ...."></textarea>';
                html += '            </div>';
                html += '        </div>';
                html += '    </div>';
                html += '</div>';

                return html;
            }
        });
    </script>
    
@endsection

resources/views/admin/crm/evaluaciones/entrenamientos/index.blade.php
@extends('admin.template.base')

@section('content')

    <div class="row clearfix">
        <div class="col-xs-12">
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('home.index') }}">
                        <i class="material-icons">home</i>&nbsp;Inicio
                    </a>
                </li>
                <li>
                    <i class="material-icons">work</i>&nbsp;Clientes
                </li>
                <li>
                    <a>
                        {{ $cliente->getFullName() }}
                    </a>
                </li>
                <li class="active">
                    Evaluaciones Entrenamientos
                </li>
            </ol>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        {{ strtoupper($cliente->getFullName()) . ' - EVALUACIONES ENTRENAMIENTOS' }}
					</h2>
					<ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="{{ route('crm.clients.evaluations.trainers.create', $cliente->id) }}">Agregar Evaluación</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="body">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation">
                            <a href="{{ route('crm.clients.show', $cliente->id) }}" aria-expanded="false">
                                <i class="material-icons">account_circle</i>&nbsp;PERFIL
                            </a>
                        </li>
                        <li role="presentation" class="active">
                            <a href="{{ route('crm.clients.evaluations.trainers.index', $cliente->id) }}" aria-expanded="false">
                                <i class="material-icons">assignment</i>&nbsp;EVALUACION ENTRENAMIENTO
                            </a>
                        </li>
                        <li role="presentation">
                            <a href="{{ route('crm.clients.evaluations.nutritionists.index', $cliente->id) }}" aria-expanded="false">
                                <i class="material-icons">assignment</i>&nbsp;EVALUACION NUTRICIONAL
                            </a>
                        </li>
                    </ul>
                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane fade active in" id="fit">                            									
							@if($cliente->evaluacionesCliente->isNotEmpty())
								<div class="m-t-20">
									<div class="panel-group" id="{{ 'accordion_' . $cliente->id }}" role="tablist" aria-multiselectable="true">										
										@foreach($cliente->evaluacionesCliente as $evaluacion)
											<div class="panel panel-primary">
												<div class="panel-heading" role="tab" id="{{ 'headingOne_' . $evaluacion->id }}">
													<h4 class="panel-title">
														<a role="button" data-toggle="collapse" data-parent="{{ 'accordion_' . $cliente->id }}" href="{{ '#collapseOne_' . $evaluacion->id }}" aria-expanded="false" aria-controls="{{ 'collapseOne_' . $evaluacion->id }}" class="collapsed">
															<div class="row box-panel-title">
                                                                <div class="col-xs-12" style="margin-bottom: 0;">
                                                                    <div class="pull-left">
                                                                        {{ 'Evaluación #' . $evaluacion->id . ' | ' . $evaluacion->fecha->format('d') . ' ' . ucwords($evaluacion->fecha->monthName) . ' ' . $evaluacion->fecha->format('Y') }}
                                                                    </div>
                                                                    <div class="pull-right">
                                                                        <i class="material-icons btn-edit-evaluation" data-link="{{ route('crm.clients.evaluations.trainers.edit', [$cliente->id, $evaluacion->id]) }}">mode_edit</i>
                                                                        <i class="material-icons btn-delete-evaluation" data-link="{{ route('crm.clients.evaluations.trainers.delete', [$cliente->id, $evaluacion->id]) }}">delete_forever</i>
                                                                    </div>
                                                                </div>
                                                            </div>
														</a>
													</h4>
												</div>
												<div id="{{ 'collapseOne_' . $evaluacion->id }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="{{ 'headingOne_' . $evaluacion->id }}" aria-expanded="false" style="height: 0px;">
													<div class="panel-body">
														<div id="wizard_horizontal">
															@foreach($evaluacion->itemsEvaluacion as $item)
																<h2>{{ $item->pregunta }}</h2>
																<section>
																	<p class="text-justify">
																		{{ $item->respuesta }}
																	</p>
																</section>
															@endforeach
														</div>
													</div>
												</div>
											</div>
										@endforeach
									</div>
								</div>
							@endif
                        </div>                        
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')

	@parent
	<!-- Jquery Validation Plugin Css -->
    <script src="{{ asset('assets/admin/plugins/jquery-validation/jquery.validate.js') }}"></script>
	<!-- JQuery Steps Plugin Js -->	
	<script src="{{ asset('assets/admin/plugins/jquery-steps/jquery.steps.js') }}"></script>
	<!-- Custom Js -->
    <script src="{{ asset('assets/admin/js/pages/forms/form-wizard.js') }}"></script>
    <script>
        $(function () {
            $(document).on('click', '.btn-edit-evaluation', function(event) {
                event.preventDefault();
                event.stopPropagation();
                $(location).attr('href', $(this).attr('data-link'));
            });

            $(document).on('click', '.btn-delete-evaluation', function(event) {
                event.preventDefault();
                event.stopPropagation();
                console.log('delete evaluation');
            });
        });
    </script>
	
@endsection