routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['verify' => true]);

Route::middleware(['auth', 'checkUserSession'])->prefix('administracion')->group(function() {
    
    Route::prefix('/')->name('home.')->group(function () {

        Route::get('/', 'Admin\HomeController@index')->name('index');

        Route::get('profile', 'Admin\HomeController@profile')->name('profile');

        Route::post('profile', 'Admin\HomeController@updateProfile')->name('update-profile');

        Route::post('cancel', 'Admin\HomeController@cancel')->name('cancel');
    });

    Route::prefix('crm')->name('crm.')->group(function () {

        Route::prefix('facturas')->name('invoices.')->group(function () {

            Route::get('/', 'Admin\FacturasController@index')->middleware(['role:superadministrador|administrador'])->name('index');

            Route::get('{id}/detalle', 'Admin\FacturasController@show')->middleware(['role:superadministrador|administrador|vendedor'])->name('show');

            Route::get('{id}/editar', 'Admin\FacturasController@edit')->middleware(['role:superadministrador|administrador'])->name('edit');

            Route::post('{id}/editar', 'Admin\FacturasController@update')->middleware(['role:superadministrador|administrador'])->name('update');

            Route::post('{id}/aprobar', 'Admin\FacturasController@approve')->middleware(['role:superadministrador|administrador'])->name('approve');

            Route::post('{id}/anular', 'Admin\FacturasController@cancel')->middleware(['role:superadministrador|administrador'])->name('cancel');
        });

        Route::prefix('clientes')->middleware(['role:superadministrador|administrador'])->name('clients.')->group(function () {

            Route::get('/', 'Admin\ClientesController@index')->name('index');

            Route::get('pendientes', 'Admin\ClientesController@indexPending')->name('index-pending');

            Route::get('nuevo', 'Admin\ClientesController@create')->name('create');

            Route::post('nuevo', 'Admin\ClientesController@store')->name('store');

            Route::get('{id}/ficha', 'Admin\ClientesController@show')->name('show');

            Route::get('{id}/editar', 'Admin\ClientesController@edit')->name('edit');

            Route::post('{id}/editar', 'Admin\ClientesController@update')->name('update');

            Route::post('{id}/eliminar', 'Admin\ClientesController@delete')->name('delete');

            Route::post('{id}/activar', 'Admin\ClientesController@activate')->name('activate');

            Route::post('{id}/suspender', 'Admin\ClientesController@suspend')->name('suspend');

            Route::post('{id}/anular', 'Admin\ClientesController@cancel')->name('cancel');

            Route::post('{id}/contactar', 'Admin\ClientesController@contact')->name('contact');

            Route::prefix('{id}/evaluaciones')->middleware(['role:superadministrador|administrador'])->name('evaluations.')->group(function () {

                Route::prefix('entrenamientos')->middleware(['role:superadministrador|administrador'])->name('trainers.')->group(function () {

                    Route::get('/', 'Admin\EvaluacionesController@trainers')->name('index');

                    Route::get('nuevo', 'Admin\EvaluacionesController@createTrainers')->name('create');

                    Route::post('nuevo', 'Admin\EvaluacionesController@storeTrainers')->name('store');

                    Route::get('{evaluation}/editar', 'Admin\EvaluacionesController@editTrainers')->name('edit');

                    Route::post('{evaluation}/editar', 'Admin\EvaluacionesController@updateTrainers')->name('update');

                    Route::post('{evaluation}/eliminar', 'Admin\EvaluacionesController@deleteTrainers')->name('delete');
                });

                Route::prefix('nutricionistas')->middleware(['role:superadministrador|administrador'])->name('nutritionists.')->group(function () {
    
                    Route::get('/', 'Admin\EvaluacionesController@nutritionist')->name('index');

                    Route::get('nuevo', 'Admin\EvaluacionesController@createNutritionist')->name('create');

                    Route::post('nuevo', 'Admin\EvaluacionesController@storeNutritionist')->name('store');

                    Route::get('{evaluation}/editar', 'Admin\EvaluacionesController@editNutritionist')->name('edit');

                    Route::post('{evaluation}/editar', 'Admin\EvaluacionesController@updateNutritionist')->name('update');

                    Route::post('{evaluation}/eliminar', 'Admin\EvaluacionesController@deleteNutritionist')->name('delete');
                });

                Route::prefix('{evaluation}/items')->middleware(['role:superadministrador|administrador'])->name('items.')->group(function () {

                    Route::post('{item}/editar', 'Admin\EvaluacionesController@updateItem')->name('update');

                    Route::post('{item}/eliminar', 'Admin\EvaluacionesController@deleteItem')->name('delete');
                });
            });
        });

        Route::prefix('entrenadores')->middleware(['role:superadministrador|administrador'])->name('trainers.')->group(function () {

            Route::get('/', 'Admin\EntrenadoresController@index')->name('index');

            Route::get('nuevo', 'Admin\EntrenadoresController@create')->name('create');

            Route::post('nuevo', 'Admin\EntrenadoresController@store')->name('store');

            Route::get('{id}/detalle', 'Admin\EntrenadoresController@detail')->name('detail');

            Route::get('{id}/editar', 'Admin\EntrenadoresController@edit')->name('edit');

            Route::post('{id}/editar', 'Admin\EntrenadoresController@update')->name('update');

            Route::post('{id}/eliminar', 'Admin\EntrenadoresController@delete')->name('delete');

            Route::post('{id}/activar', 'Admin\EntrenadoresController@activate')->name('activate');

            Route::post('{id}/suspender', 'Admin\EntrenadoresController@suspend')->name('suspend');

            Route::post('{id}/anular', 'Admin\EntrenadoresController@cancel')->name('cancel');
        });

        Route::prefix('nutricionistas')->middleware(['role:superadministrador|administrador'])->name('nutritionists.')->group(function () {

            Route::get('/', 'Admin\NutricionistasController@index')->name('index');

            Route::get('nuevo', 'Admin\NutricionistasController@create')->name('create');

            Route::post('nuevo', 'Admin\NutricionistasController@store')->name('store');

            Route::get('{id}/detalle', 'Admin\NutricionistasController@detail')->name('detail');

            Route::get('{id}/editar', 'Admin\NutricionistasController@edit')->name('edit');

            Route::post('{id}/editar', 'Admin\NutricionistasController@update')->name('update');

            Route::post('{id}/eliminar', 'Admin\NutricionistasController@delete')->name('delete');

            Route::post('{id}/activar', 'Admin\NutricionistasController@activate')->name('activate');

            Route::post('{id}/suspender', 'Admin\NutricionistasController@suspend')->name('suspend');

            Route::post('{id}/anular', 'Admin\NutricionistasController@cancel')->name('cancel');
        });

        /*Route::prefix('informes')->middleware(['role:superadministrador|administrador'])->name('reports.')->group(function () {

            Route::get('/', 'Admin\InformesController@index')->name('index');

            Route::get('proccess', 'Admin\InformesController@proccess')->name('proccess');
        });*/
    });

    Route::prefix('configuracion')->name('configuration.')->group(function () {

        Route::prefix('planes')->middleware(['role:superadministrador|administrador'])->name('plans.')->group(function () {

            Route::get('/', 'Admin\PlanesController@index')->name('index');

            Route::get('nuevo', 'Admin\PlanesController@create')->name('create');

            Route::post('nuevo', 'Admin\PlanesController@store')->name('store');

            Route::get('{id}/editar', 'Admin\PlanesController@edit')->name('edit');

            Route::post('{id}/editar', 'Admin\PlanesController@update')->name('update');

            Route::post('{id}/eliminar', 'Admin\PlanesController@delete')->name('delete');

            Route::post('{id}/suspender', 'Admin\PlanesController@suspend')->name('suspend');

            Route::post('{id}/activar', 'Admin\PlanesController@activate')->name('activate');
        });

        Route::prefix('usuarios')->middleware(['role:superadministrador|administrador'])->name('users.')->group(function () {

            Route::get('/', 'Admin\UsuariosController@index')->name('index');

            Route::get('nuevo', 'Admin\UsuariosController@create')->name('create');

            Route::post('nuevo', 'Admin\UsuariosController@store')->name('store');

            Route::get('{id}/editar', 'Admin\UsuariosController@edit')->name('edit');

            Route::post('{id}/editar', 'Admin\UsuariosController@update')->name('update');

            Route::post('{id}/eliminar', 'Admin\UsuariosController@delete')->name('delete');

            Route::post('{id}/suspender', 'Admin\UsuariosController@suspend')->name('suspend');

            Route::post('{id}/activar', 'Admin\UsuariosController@activate')->name('activate');
        });        
    });
});

app/Http/Controllers/Admin/UsuariosController.php
<?php

namespace App\Http\Controllers\Admin;

use Exception;
use App\Globals\Alerts;
use App\Http\Controllers\Controller;
use App\Http\Requests\CreateUserRequest;
use App\Http\Requests\EditUserRequest;
use App\Repositories\Roles\RolesRepoI;
use App\Repositories\Usuarios\UsuariosRepoI;
use Illuminate\Http\Request;

class UsuariosController extends Controller
{
    protected $rolesRepo, $usuariosRepo;

    public function __construct(RolesRepoI $rolesRepo, UsuariosRepoI $usuariosRepo)
    {
        $this->rolesRepo = $rolesRepo;
        $this->usuariosRepo = $usuariosRepo;
    }

    public function index()
    {   
        $users = $this->usuariosRepo->getAllUsers();

        return view('admin.configuracion.usuarios.index', [
            'users' => $users
        ]);
    }

    public function create()
    {
        $roles = $this->rolesRepo->getRolesList();

        return view('admin.configuracion.usuarios.create', [
            'roles' => $roles
        ]);
    }

    public function store(CreateUserRequest $request)
    {
        try {

            $data = [
                'name'     => $request->name,
                'email'    => $request->email,
                'password' => bcrypt($request->password),
            ];

            $this->usuariosRepo->createUser($data, $request->role);

            return redirect()->route('configuration.users.index')
                ->with('message', Alerts::CREATE_SUCCESS)
                ->with('messageType', 'success');

        } catch (Exception $e) {
            throw $e;
        }
    }

    public function edit($id)
    {
        $roles = $this->rolesRepo->getRolesList();
        $user = $this->usuariosRepo->findOneBy(['id' => $id]);
        $roleUser = $user->roles->first();

        return view('admin.configuracion.usuarios.edit', [
            'roles'    => $roles,
            'roleUser' => $roleUser,
            'user'     => $user
        ]);
    }

    public function update($id, EditUserRequest $request)
    {
        try {
            $data = [
                'name'  => $request->name,
                'email' => $request->email,
            ];

            if ($request->password) {
                $data['password'] = bcrypt($request->password);
            }

            $this->usuariosRepo->updateUser($id, $data, $request->role);

            return redirect()->route('configuration.users.index')
                ->with('message', Alerts::UPDATE_SUCCESS)
                ->with('messageType', 'success');

        } catch (Exception $e) {
            throw $e;
        }
    }

    public function delete($id, Request $request)
    {
        $this->usuariosRepo->deleteBy(['id' => $id]);

        return redirect()->back()
            ->with('message', Alerts::DELETE_SUCCESS)
            ->with('messageType', 'success');
    }

    public function suspend($id, Request $request)
    {
        $this->usuariosRepo->suspend($id);

        return redirect()->back()
            ->with('message', Alerts::SUSPEND_SUCCESS)
            ->with('messageType', 'success');
    }

    public function activate($id, Request $request)
    {
        $this->usuariosRepo->activate($id);

        return redirect()->back()
            ->with('message', Alerts::ACTIVATE_SUCCESS)
            ->with('messageType', 'success');
    }
}

resources/views/admin/configuracion/usuarios/create.blade.php
@extends('admin.template.base')

@section('content')

    @include('admin.errors.errors')

    <div class="row clearfix">
        <div class="col-xs-12">
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('home.index') }}">
                        <i class="material-icons">home</i>&nbsp;Inicio
                    </a>
                </li>
                <li>
                    <a href="{{ route('configuration.users.index') }}">
                        <i class="material-icons">supervisor_account</i>&nbsp;Usuarios
                    </a>
                </li>
                <li class="active">
                    Nuevo
                </li>
            </ol>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>AGREGAR USUARIO</h2>
                </div>
                <div class="body">
                    {!! Form::open(['id' => 'form-create-user', 'url' => route('configuration.users.store'), 'method' => 'POST']) !!}
                        
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <label class="form-label">Nombre</label>
                                        <input type="text" class="form-control" name="name" value="{{ old('name') }}" tabindex="1">                                        
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <label class="form-label">Email</label>
                                        <input type="text" class="form-control" name="email" value="{{ old('email') }}" required="required" tabindex="2">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <label class="form-label">Rol</label>
                                        <select id="role" name="role" class="form-control" required="required" tabindex="3">
                                            <option value="">&nbsp;Seleccione un rol</option>
                                            @foreach($roles as $role)
                                                <option value="{{ $role->name }}" {{ (old('role') == $role->name) ? 'selected' : '' }}>{{ $role->display_name }}</option>
                                            @endforeach
                                        </select>                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="password" name="password" class="form-control" id="password" value="{{ old('password') }}" required="required" tabindex="4">
                                        <label class="form-label">Contraseña</label>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="password" name="password_confirmation" id="password_confirmation" class="form-control" value="{{ old('password_confirmation') }}" required="required" tabindex="5">
                                        <label class="form-label">Confirmar Contraseña</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <button class="btn btn-primary waves-effect pull-right" type="submit">Guardar</button>
                            </div>
                        </div>

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')

	@parent
	<!-- Jquery Validation Plugin Css -->
    <script src="{{ asset('assets/admin/plugins/jquery-validation/jquery.validate.js') }}"></script>
    <script>
        $(function () {
            $('#form-create-user').validate({
                rules: {
                    role: "required",
					email: {
						required: true,
						email: true
					},
					password: {
						required: true,
						minlength: 4
					},
					password_confirmation: {
						required: true,
						minlength: 4,
						equalTo: "#password"
					}
                },
                highlight: function (input) {
                    $(input).parents('.form-line').addClass('error');
                },
                unhighlight: function (input) {
                    $(input).parents('.form-line').removeClass('error');
                },
                errorPlacement: function (error, element) {
                    $(element).parents('.form-group').append(error);
                }
            });
        });
    </script>
    
@endsection

resources/views/admin/configuracion/usuarios/edit.blade.php
@extends('admin.template.base')

@section('content')

    @include('admin.errors.errors')

    <div class="row clearfix">
        <div class="col-xs-12">
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('home.index') }}">
                        <i class="material-icons">home</i>&nbsp;Inicio
                    </a>
                </li>
                <li>
                    <a href="{{ route('configuration.users.index') }}">
                        <i class="material-icons">supervisor_account</i>&nbsp;Usuarios
                    </a>
                </li>
                <li>
                    <a>
                        {{  '#' . $user->id }}
                    </a>
                </li>
                <li class="active">
                    Editar
                </li>
            </ol>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>EDITAR USUARIO {{ '#' . $user->id }}</h2>
                </div>
                <div class="body">
                    {!! Form::open(['id' => 'form-edit-user', 'url' => route('configuration.users.update', $user->id), 'method' => 'POST']) !!}
                        
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <label class="form-label">Nombre</label>
                                        <input type="text" class="form-control" name="name" value="{{ (old('name')) ? old('name') : $user->name }}" tabindex="1">                                        
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <label class="form-label">Email</label>
                                        <input type="text" class="form-control" name="email" value="{{ (old('name')) ? old('email') : $user->email }}" required="required" tabindex="2">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <label class="form-label">Rol</label>
                                        <select id="role" name="role" class="form-control" required="required" tabindex="3">
                                            <option value="">&nbsp;Seleccione un rol</option>
                                            @foreach($roles as $role)
                                                @if(old('role'))
                                                    <option value="{{ $role->name }}" {{ (old('role') === $role->name) ? 'selected' : '' }}>{{ $role->display_name }}</option>
                                                @else
                                                    <option value="{{ $role->name }}" {{ ($roleUser->name === $role->name) ? 'selected' : '' }}>{{ $role->display_name }}</option>
                                                @endif
                                            @endforeach
                                        </select>                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="password" name="password" class="form-control" id="password" value="{{ old('password') }}" tabindex="4">
                                        <label class="form-label">Contraseña</label>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        <input type="password" name="password_confirmation" id="password_confirmation" class="form-control" value="{{ old('password_confirmation') }}" tabindex="5">
                                        <label class="form-label">Confirmar Contraseña</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <button class="btn btn-primary waves-effect pull-right" type="submit">Guardar</button>
                            </div>
                        </div>

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')

	@parent
	<!-- Jquery Validation Plugin Css -->
    <script src="{{ asset('assets/admin/plugins/jquery-validation/jquery.validate.js') }}"></script>
    <script>
        $(function () {
            $('#form-create-user').validate({
                rules: {
                    role: "required",
					email: {
						required: true,
						email: true
					},
					password: {
						minlength: 4
					},
					password_confirmation: {
						minlength: 4,
						equalTo: "#password"
					}
                },
                highlight: function (input) {
                    $(input).parents('.form-line').addClass('error');
                },
                unhighlight: function (input) {
                    $(input).parents('.form-line').removeClass('error');
                },
                errorPlacement: function (error, element) {
                    $(element).parents('.form-group').append(error);
                }
            });
        });
    </script>
    
@endsection

resources/views/admin/configuracion/usuarios/index.blade.php
@extends('admin.template.base')

@section('styles')

	@parent
	<!-- JQuery DataTable Css -->
    <link href="{{ asset('assets/admin/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}" rel="stylesheet" />    
	
@endsection

@section('content')

    <div class="row clearfix">
        <div class="col-xs-12">
            <ol class="breadcrumb">
                <li>
                    <a href="{{ route('home.index') }}">
                        <i class="material-icons">home</i>&nbsp;Inicio
                    </a>
                </li>
                <li class="active">
                    <i class="material-icons">supervisor_account</i>&nbsp;Usuarios
                </li>
            </ol>
        </div>
    </div>
    <div class="row clearfix">
        <div class="col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        LISTADO DE USUARIOS
                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <li class="dropdown">
                            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <i class="material-icons">more_vert</i>
                            </a>
                            <ul class="dropdown-menu pull-right">
                                <li><a href="{{ route('configuration.users.create') }}">Agregar Usuario</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                            <thead>
                                <tr>
                                    <th>Nombre</th>
                                    <th>Email</th>
                                    <th>Rol</th>
                                    <th>Estado</th>
                                    <th>Creado</th>
                                    <th>Modificado</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>Nombre</th>
                                    <th>Email</th>
                                    <th>Rol</th>
                                    <th>Estado</th>
                                    <th>Creado</th>
                                    <th>Modificado</th>
                                    <th>Acciones</th>
                                </tr>
                            </tfoot>
                            <tbody>
                                @foreach($users as $user)
                                    <tr>
                                        <td>{{ $user->getFullName() }}</td>
                                        <td><a href="mailto:{{ $user->email }}">{{ $user->email }}</a></td>
                                        <td>{{ $user->roles->first()->display_name }}</td>
                                        <td>{{ $user->getStatus() }}</td>
                                        <td>{{ $user->created_at->diffForHumans() }}</td>
                                        <td>{{ $user->updated_at->diffForHumans() }}</td>
                                        <td>
                                            <a href="{{ route('configuration.users.edit', $user->id) }}" title="Editar">
                                                <i class="material-icons">mode_edit</i>
                                            </a>
                                            <a href="{{ route('configuration.users.delete', $user->id) }}" class="btn-request-post" title="Eliminar">
                                                <i class="material-icons">delete_forever</i>
                                            </a>

                                            @if($user->status)
                                                <a href="{{ route('configuration.users.suspend', $user->id) }}" class="btn-request-post" title="Suspender">
                                                    <i class="material-icons">visibility_off</i>
                                                </a>
                                            @else
                                                <a href="{{ route('configuration.users.activate', $user->id) }}" class="btn-request-post" title="Activar">
                                                    <i class="material-icons">restore</i>
                                                </a>
                                            @endif
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')

	@parent
	<!-- Jquery DataTable Plugin Js -->
    <script src="{{ asset('assets/admin/plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('assets/admin/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('assets/admin/js/pages/tables/jquery-datatable.js') }}"></script>
    
@endsection